package ${basePkg}.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class Base${tableName?cap_first} extends BaseModel implements IBean {

}
